# Generated by Django 5.2.8 on 2025-12-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
    ]
